(ns pgmalli.impl.files
  "Config -> generated EDN files, one per schema. The config is documented on pgmalli.generate.

   File contents, in this order:
     {:schema \"public\" :database-version \"PostgreSQL 17.6\" :diagnostics [...]
      :registry {name schema} :unrendered [fact ...] :skipped [fact ...]}

   Output is deterministic (sorted maps, pprint). Overrides that are not EDN (functions)
   are rejected at generation time."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.pprint :as pp]
            [clojure.walk :as walk]
            [pgmalli.impl.ir :as ir]
            [pgmalli.impl.pattern :as pattern]
            [pgmalli.impl.render :as render]))

(def default-config {:schemas ["public"] :out-dir "resources/pgmalli" :overrides {} :db {}})

(defn config
  "Config with defaults applied. Unknown keys are an error."
  [c]
  (when-let [unknown (seq (remove (set (keys default-config)) (keys c)))]
    (throw (ex-info (str "unknown config keys: " (pr-str unknown) "; valid keys are " (pr-str (keys default-config)))
                    {:unknown unknown})))
  (merge default-config c))

(defn- sort-maps [x]
  (walk/postwalk #(if (map? %) (into (sorted-map-by (fn [a b] (compare (str a) (str b)))) %) %) x))

(defn assemble
  "The file's data from the rendering of a schema's facts, in reading order: what it is, then
   what deserves a look, then the schemas, then what was left out."
  [schema database-version facts overrides]
  (let [r (sort-maps (render/rendered facts (or overrides {})))]
    (array-map :schema schema :database-version database-version
               :diagnostics (:diagnostics r) :registry (:registry r) :unrendered (:unrendered r) :skipped (:skipped r))))

(defn from-database
  "Generated data for one schema, read from the database."
  [{:keys [db overrides]} schema]
  (let [ir (ir/from-db (assoc db :schema schema))]
    (assemble schema (:database_version ir) (pattern/facts ir) overrides)))

(defn path-for
  "Where a schema's file goes: <out-dir>/<schema>.edn."
  [c schema]
  (str (io/file (:out-dir (config c)) (str schema ".edn"))))

(defn generated-all
  "{schema {:path :data}} for every schema in the config."
  [c]
  (let [c (config c)]
    (into {} (for [s (:schemas c)] [s {:path (path-for c s) :data (from-database c s)}]))))

(defn edn-string
  "The file's text: a deterministic pprint of the data behind the do-not-edit header. Data that
   does not read back as EDN is an error."
  [data]
  (let [s (binding [pp/*print-right-margin* 100
                    *print-namespace-maps* false]
            (with-out-str (pp/pprint data)))]
    (when-not (= data (try (edn/read-string s) (catch Exception _ ::unreadable)))
      (throw (ex-info "generated data is not readable EDN; overrides must be data such as [:ref name], not functions"
                      {:data data})))
    (str ";; generated by pgmalli; do not edit (adjust :overrides instead)\n" s)))

(defn generate!
  "Writes every schema's file. Returns {schema path}."
  [c]
  (into {} (for [[schema {:keys [path data]}] (generated-all c)]
             (do (io/make-parents path)
                 (spit path (edn-string data))
                 [schema path]))))

(defn read-edn
  "The generated data in a file, by path (pgmalli.impl.registry reads the classpath instead)."
  [path]
  (edn/read-string (slurp path)))
