(ns pgmalli.impl.generate
  "Config -> generated EDN files, one per schema.

   Config:
     {:schemas [\"public\"]           ; default [\"public\"]
      :out-dir \"resources/pgmalli\"  ; default; files are <out-dir>/<schema>.edn
      :checks :data                    ; default; :fn also compiles cross-column CHECKs into [:fn ...]
      :overrides {constraint-name schema-or-{:skip reason}}
      :db {:host :port :db :user :password :sslmode :psql}}  ; optional; psql's environment otherwise

   File contents:
     {:schema \"public\" :database-version \"PostgreSQL 17.x ...\"
      :registry {name schema} :unrendered [fact ...] :skipped [fact ...]}

   Output is deterministic (sorted maps, pprint). Overrides that are not EDN (functions)
   are rejected at generation time."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.pprint :as pp]
            [clojure.walk :as walk]
            [pgmalli.impl.ir :as ir]
            [pgmalli.impl.pattern :as pattern]
            [pgmalli.impl.render :as render]))

(def default-config {:schemas ["public"] :out-dir "resources/pgmalli" :checks :data :overrides {} :db {}})

(defn config
  "Config with defaults applied. Unknown keys are an error."
  [c]
  (when-let [unknown (seq (remove (set (keys default-config)) (keys c)))]
    (throw (ex-info (str "unknown config keys: " (pr-str unknown) "; valid keys are " (pr-str (keys default-config)))
                    {:unknown unknown})))
  (merge default-config c))

(defn- sort-maps [x]
  (walk/postwalk #(if (map? %) (into (sorted-map-by (fn [a b] (compare (str a) (str b)))) %) %) x))

(defn generated
  "Generated data for one schema."
  [{:keys [db overrides checks]} schema]
  (let [ir (ir/from-db (assoc db :schema schema))]
    (sort-maps
     (merge {:schema schema :database-version (:database_version ir)}
            (render/registry (pattern/facts ir) (or overrides {}) {:checks (or checks :data)})))))

(defn path-for [c schema]
  (str (io/file (:out-dir (config c)) (str schema ".edn"))))

(defn generated-all
  "{schema {:path :data}} for every schema in the config."
  [c]
  (let [c (config c)]
    (into {} (for [s (:schemas c)] [s {:path (path-for c s) :data (generated c s)}]))))

(defn edn-string [data]
  (let [s (binding [pp/*print-right-margin* 100
                    *print-namespace-maps* false]
            (with-out-str (pp/pprint data)))]
    (when-not (= data (try (edn/read-string s) (catch Exception _ ::unreadable)))
      (throw (ex-info "generated data is not readable EDN; overrides must be data such as [:ref name], not functions"
                      {:data data})))
    (str ";; generated by pgmalli; do not edit (adjust :overrides instead)\n" s)))

(defn generate!
  "Writes every schema's file. Returns {schema path}."
  [c]
  (into {} (for [[schema {:keys [path data]}] (generated-all c)]
             (do (io/make-parents path)
                 (spit path (edn-string data))
                 [schema path]))))

(defn load-file* [path]
  (edn/read-string (slurp path)))
