(ns pgmalli.core-test
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is testing use-fixtures]]
            clojure.test.check.generators
            honey.sql
            [malli.core :as m]
            [pgmalli.core :as pgmalli]
            [pgmalli.impl.generate :as gen]
            [pgmalli.test-db :refer [*db* exec-sql! with-postgres]])
  (:import (java.io File)))

(use-fixtures :once with-postgres)

(deftest generated-data-must-be-edn
  (is (thrown? clojure.lang.ExceptionInfo (gen/edn-string {:registry {:x [:fn (fn [_] true)]}})))
  (let [s (gen/edn-string {:registry {:pg.public/t [:map [:a ['inst? {:pg/type "timestamptz"}]]]}})]
    (is (str/starts-with? s ";; generated by pgmalli"))
    (is (not (str/includes? s "#:pg")))))

(deftest unknown-config-keys-are-rejected
  (is (thrown-with-msg? clojure.lang.ExceptionInfo #"unknown config keys" (gen/config {:out_dir "x"}))))

(deftest generate-check-roundtrip
  (when *db*
    (let [out-dir (str (doto (File/createTempFile "pgmalli-gen" "") .delete))
          config {:db *db* :out-dir out-dir}
          out (gen/path-for config "public")]
      (exec-sql! "CREATE TYPE mood AS ENUM ('happy', 'sad');
                  CREATE TABLE users (id bigint PRIMARY KEY, mood mood NOT NULL DEFAULT 'happy',
                                      age integer CHECK (age >= 0), nick varchar(40) CHECK (length(TRIM(BOTH FROM nick)) > 0),
                                      closed_at timestamptz, CONSTRAINT closed CHECK (mood = 'sad' OR closed_at IS NULL));
                  CREATE UNIQUE INDEX users_nick_idx ON users (nick);
                  CREATE UNIQUE INDEX users_nick_lower_idx ON users (lower(nick));
                  CREATE UNIQUE INDEX users_age_open_idx ON users (age) WHERE closed_at IS NULL;
                  CREATE UNIQUE INDEX users_age_inc_idx ON users (age) INCLUDE (nick);
                  CREATE UNIQUE INDEX closed ON users (closed_at);
                  CREATE TABLE prices (id integer PRIMARY KEY, p1 numeric(3,1), p2 numeric(3,5), p3 numeric(2,-3));
                  CREATE TABLE parted (k integer NOT NULL, v text) PARTITION BY RANGE (k);
                  CREATE TABLE parted_low PARTITION OF parted FOR VALUES FROM (0) TO (100);
                  CREATE TABLE parted_high PARTITION OF parted FOR VALUES FROM (100) TO (200);
                  CREATE TABLE nopart (k integer) PARTITION BY LIST (k);
                  CREATE FUNCTION touch() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;
                  CREATE TRIGGER users_touch BEFORE INSERT ON users FOR EACH ROW EXECUTE FUNCTION touch();")
      (testing "a missing file is stale"
        (is (every? (comp nil? :file) (get (pgmalli/stale config) "public"))))
      (testing "generate, read back, validate"
        (is (= {"public" out} (pgmalli/generate! config)))
        (let [data (gen/load-file* out)]
          (is (= data (get-in (gen/generated-all config) ["public" :data])))
          (is (= (slurp out) (do (pgmalli/generate! config) (slurp out))) "byte-for-byte deterministic")
          (is (empty? (:unrendered data)) "the table CHECK is a :multi")
          (let [reg (pgmalli/registry data)]
            (is (m/validate :pg.public/users {:id 1 :mood "sad" :age 3 :nick "n" :closed_at nil} {:registry reg}))
            (is (not (m/validate :pg.public/users {:id 1 :mood "sad" :age -1 :nick "n" :closed_at nil} {:registry reg})))
            (is (not (m/validate :pg.public/users {:id 1 :mood "happy" :age 1 :nick "n" :closed_at (java.time.Instant/now)} {:registry reg}))
                "closed_at only when sad")
            (is (m/validate :pg.public.users/insert {:id 1 :nick "n"} {:registry reg}) "defaults and nullable columns may be omitted")
            (is (= [{:columns ["age"]} {:columns ["closed_at"]} {:columns ["nick"]}] (let [s (:pg.public/users reg)] (:pg/unique (second (if (= :and (first s)) (second s) s)))))
                "unique indexes over plain columns count, key columns only, even one named as a constraint is; expression and partial ones do not")
            (is (some #(= "closed" (:error/message (second %))) (drop 2 (:pg.public/users reg))) "the CHECK of that name is there too")
            (let [col (fn [k] (pgmalli/non-null (pgmalli/column reg :pg.public/prices k)))]
              (is (= [[:pg/numeric {:precision 3 :scale 1}] [:pg/numeric {:precision 3 :scale 5}] [:pg/numeric {:precision 2 :scale -3}]]
                     (map #(last (col %)) [:p1 :p2 :p3]))
                  "the scale is read as PostgreSQL stores it, signed")
              (doseq [[k ok bad] [[:p1 99.94M 99.95M] [:p2 0.00999M 0.01M] [:p3 99000M 99500M]]]
                (is (m/validate (col k) ok {:registry reg}))
                (is (not (m/validate (col k) bad {:registry reg})))
                (exec-sql! (str "INSERT INTO prices (id, " (name k) ") VALUES (" (rand-int 1000000) ", " ok ")"))
                (is (thrown-with-msg? clojure.lang.ExceptionInfo #"numeric field overflow"
                                      (exec-sql! (str "INSERT INTO prices (id, " (name k) ") VALUES (" (rand-int 1000000) ", " bad ")")))
                    (str k ": the database draws the line where the schema does")))
              (is (m/validate :pg.public/parted {:k 150 :v nil} {:registry reg}))
              (is (not (m/validate :pg.public/parted {:k 250 :v nil} {:registry reg})) "no partition takes 250: the row schema says so")
              (is (every? #(< -1 (:k %) 200) (get (clojure.test.check.generators/generate (pgmalli/dataset-generator reg {:rows 5}) 30 1) "public.parted"))
                  "generated rows land in a partition")
              (is (= [{:kind :no-partition :table "public.nopart"} {:kind :row-trigger :table "public.users"}] (map #(select-keys % [:kind :table]) (:diagnostics data)))
                  "the file says what deserves a look")))))
      (testing "stale and unrendered"
        (is (nil? (pgmalli/stale config)))
        (is (empty? (:unrendered (gen/load-file* out))))
        (exec-sql! "ALTER TABLE users ADD COLUMN extra int;")
        (let [diffs (get (pgmalli/stale config) "public")]
          (is (= [[:pg.public/users :extra]] (map (juxt :name :column) diffs))
              "a new column shows as itself, in the row schema (the insert schema is derived at load, not in the file)")
          (is (every? (comp nil? :file) diffs)))))))

(deftest inserts-load-into-the-database
  (when *db*
    (let [out-dir (str (doto (File/createTempFile "pgmalli-ins" "") .delete))
          config {:db *db* :out-dir out-dir}]
      (exec-sql! "CREATE SCHEMA ins;
                  CREATE TYPE ins.mood AS ENUM ('happy', 'sad');
                  CREATE TABLE ins.groups (id integer PRIMARY KEY, name text NOT NULL UNIQUE);
                  CREATE TABLE ins.users (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                          group_id integer NOT NULL REFERENCES ins.groups,
                                          parent_id bigint REFERENCES ins.users,
                                          mood ins.mood NOT NULL DEFAULT 'happy',
                                          nick text NOT NULL CHECK (nick <> ''),
                                          nick_upper text GENERATED ALWAYS AS (upper(nick)) STORED,
                                          tags text[] NOT NULL DEFAULT '{}',
                                          meta jsonb);
                  CREATE TABLE ins.hashed (k integer NOT NULL, s text NOT NULL, u uuid) PARTITION BY HASH (k, s, u);
                  CREATE TABLE ins.hashed_0 PARTITION OF ins.hashed FOR VALUES WITH (MODULUS 4, REMAINDER 0);
                  CREATE TABLE ins.hashed_1 PARTITION OF ins.hashed FOR VALUES WITH (MODULUS 4, REMAINDER 1);
                  CREATE TABLE ins.hashed_3 PARTITION OF ins.hashed FOR VALUES WITH (MODULUS 4, REMAINDER 3);")
      (pgmalli/generate! (assoc config :schemas ["ins"]))
      (let [registry (pgmalli/registry (gen/load-file* (gen/path-for config "ins")))
            dataset (clojure.test.check.generators/generate (pgmalli/dataset-generator registry {:rows 4}) 30 7)
            statements (pgmalli/inserts registry dataset)
            counts (fn [] (str/join " " (for [t ["ins.groups" "ins.users" "ins.hashed"]]
                                          (str "IF (SELECT count(*) FROM " t ") <> " (count (get dataset t))
                                               " THEN RAISE EXCEPTION '" t " has the wrong number of rows'; END IF;"))))]
        (is (= [:ins.groups :ins.hashed [{:overriding-value :system} :ins.users]] (map :insert-into statements)))
        (is (= 4 (count (get dataset "ins.hashed"))) "every generated row lands in one of the three partitions (remainder 2 has none): routed as the database routes")
        (exec-sql! (str (str/join ";\n" (map #(first (honey.sql/format % {:inline true})) statements)) ";\n"
                        "DO $$ BEGIN " (counts) " END $$;"))
        (is true "every INSERT ran, identity ids kept, generated column left to the database")))))
