(ns pgmalli.core-test
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is testing use-fixtures]]
            [malli.core :as m]
            [pgmalli.core :as pgmalli]
            [pgmalli.impl.generate :as gen]
            [pgmalli.test-db :refer [*db* exec-sql! with-postgres]])
  (:import (java.io File)))

(use-fixtures :once with-postgres)

(deftest generated-data-must-be-edn
  (is (thrown? clojure.lang.ExceptionInfo (gen/edn-string {:registry {:x [:fn (fn [_] true)]}})))
  (let [s (gen/edn-string {:registry {:pg.public/t [:map [:a ['inst? {:pg/type "timestamptz"}]]]}})]
    (is (str/starts-with? s ";; generated by pgmalli"))
    (is (not (str/includes? s "#:pg")))))

(deftest unknown-config-keys-are-rejected
  (is (thrown-with-msg? clojure.lang.ExceptionInfo #"unknown config keys" (gen/config {:out_dir "x"}))))

(deftest generate-check-roundtrip
  (when *db*
    (let [out-dir (str (doto (File/createTempFile "pgmalli-gen" "") .delete))
          config {:db *db* :out-dir out-dir}
          out (gen/path-for config "public")]
      (exec-sql! "CREATE TYPE mood AS ENUM ('happy', 'sad');
                  CREATE TABLE users (id bigint PRIMARY KEY, mood mood NOT NULL DEFAULT 'happy',
                                      age integer CHECK (age >= 0), nick varchar(40) CHECK (length(TRIM(BOTH FROM nick)) > 0),
                                      closed_at timestamptz, CONSTRAINT closed CHECK (mood = 'sad' OR closed_at IS NULL));")
      (testing "a missing file is stale"
        (is (= [nil] (map first (vals (pgmalli/stale config))))))
      (testing "generate, read back, validate"
        (is (= {"public" out} (pgmalli/generate! config)))
        (let [data (gen/load-file* out)]
          (is (= data (get-in (gen/generated-all config) ["public" :data])))
          (is (= (slurp out) (do (pgmalli/generate! config) (slurp out))) "byte-for-byte deterministic")
          (is (empty? (:unrendered data)) "the table CHECK is a :multi")
          (let [reg (pgmalli/registry data)]
            (is (m/validate :pg.public/users {:id 1 :mood "sad" :age 3 :nick "n" :closed_at nil} {:registry reg}))
            (is (not (m/validate :pg.public/users {:id 1 :mood "sad" :age -1 :nick "n" :closed_at nil} {:registry reg})))
            (is (not (m/validate :pg.public/users {:id 1 :mood "happy" :age 1 :nick "n" :closed_at (java.time.Instant/now)} {:registry reg}))
                "closed_at only when sad")
            (is (m/validate :pg.public.users/insert {:id 1 :nick "n"} {:registry reg}) "defaults and nullable columns may be omitted"))))
      (testing "stale and unrendered"
        (is (nil? (pgmalli/stale config)))
        (is (empty? (:unrendered (gen/load-file* out))))
        (exec-sql! "ALTER TABLE users ADD COLUMN extra int;")
        (is (contains? (pgmalli/stale config) "public"))))))
