(ns pgmalli.core-test
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is testing use-fixtures]]
            clojure.test.check.generators
            honey.sql
            [malli.core :as m]
            [pgmalli.core :as pgmalli]
            [pgmalli.impl.generate :as gen]
            [pgmalli.test-db :refer [*db* exec-sql! with-postgres]])
  (:import (java.io File)))

(use-fixtures :once with-postgres)

(deftest generated-data-must-be-edn
  (is (thrown? clojure.lang.ExceptionInfo (gen/edn-string {:registry {:x [:fn (fn [_] true)]}})))
  (let [s (gen/edn-string {:registry {:pg.public/t [:map [:a ['inst? {:pg/type "timestamptz"}]]]}})]
    (is (str/starts-with? s ";; generated by pgmalli"))
    (is (not (str/includes? s "#:pg")))))

(deftest unknown-config-keys-are-rejected
  (is (thrown-with-msg? clojure.lang.ExceptionInfo #"unknown config keys" (gen/config {:out_dir "x"}))))

(deftest generate-check-roundtrip
  (when *db*
    (let [out-dir (str (doto (File/createTempFile "pgmalli-gen" "") .delete))
          config {:db *db* :out-dir out-dir}
          out (gen/path-for config "public")]
      (exec-sql! "CREATE TYPE mood AS ENUM ('happy', 'sad');
                  CREATE TABLE users (id bigint PRIMARY KEY, mood mood NOT NULL DEFAULT 'happy',
                                      age integer CHECK (age >= 0), nick varchar(40) CHECK (length(TRIM(BOTH FROM nick)) > 0),
                                      closed_at timestamptz, CONSTRAINT closed CHECK (mood = 'sad' OR closed_at IS NULL));
                  CREATE UNIQUE INDEX users_nick_idx ON users (nick);
                  CREATE UNIQUE INDEX users_nick_lower_idx ON users (lower(nick));
                  CREATE UNIQUE INDEX users_age_open_idx ON users (age) WHERE closed_at IS NULL;
                  CREATE UNIQUE INDEX users_age_inc_idx ON users (age) INCLUDE (nick);
                  CREATE UNIQUE INDEX closed ON users (closed_at);")
      (testing "a missing file is stale"
        (is (every? (comp nil? :file) (get (pgmalli/stale config) "public"))))
      (testing "generate, read back, validate"
        (is (= {"public" out} (pgmalli/generate! config)))
        (let [data (gen/load-file* out)]
          (is (= data (get-in (gen/generated-all config) ["public" :data])))
          (is (= (slurp out) (do (pgmalli/generate! config) (slurp out))) "byte-for-byte deterministic")
          (is (empty? (:unrendered data)) "the table CHECK is a :multi")
          (let [reg (pgmalli/registry data)]
            (is (m/validate :pg.public/users {:id 1 :mood "sad" :age 3 :nick "n" :closed_at nil} {:registry reg}))
            (is (not (m/validate :pg.public/users {:id 1 :mood "sad" :age -1 :nick "n" :closed_at nil} {:registry reg})))
            (is (not (m/validate :pg.public/users {:id 1 :mood "happy" :age 1 :nick "n" :closed_at (java.time.Instant/now)} {:registry reg}))
                "closed_at only when sad")
            (is (m/validate :pg.public.users/insert {:id 1 :nick "n"} {:registry reg}) "defaults and nullable columns may be omitted")
            (is (= [{:columns ["age"]} {:columns ["nick"]}] (let [s (:pg.public/users reg)] (:pg/unique (second (if (= :and (first s)) (second s) s)))))
                "unique indexes over plain columns count, key columns only; expression and partial ones, and one named as a constraint is, do not")
            (is (some #(= "closed" (:error/message (second %))) (drop 2 (:pg.public/users reg))) "the CHECK named like the index is still there"))))
      (testing "stale and unrendered"
        (is (nil? (pgmalli/stale config)))
        (is (empty? (:unrendered (gen/load-file* out))))
        (exec-sql! "ALTER TABLE users ADD COLUMN extra int;")
        (let [diffs (get (pgmalli/stale config) "public")]
          (is (= [[:pg.public/users :extra]] (map (juxt :name :column) diffs))
              "a new column shows as itself, in the row schema (the insert schema is derived at load, not in the file)")
          (is (every? (comp nil? :file) diffs)))))))

(deftest inserts-load-into-the-database
  (when *db*
    (let [out-dir (str (doto (File/createTempFile "pgmalli-ins" "") .delete))
          config {:db *db* :out-dir out-dir}]
      (exec-sql! "CREATE SCHEMA ins;
                  CREATE TYPE ins.mood AS ENUM ('happy', 'sad');
                  CREATE TABLE ins.groups (id integer PRIMARY KEY, name text NOT NULL UNIQUE);
                  CREATE TABLE ins.users (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                          group_id integer NOT NULL REFERENCES ins.groups,
                                          parent_id bigint REFERENCES ins.users,
                                          mood ins.mood NOT NULL DEFAULT 'happy',
                                          nick text NOT NULL CHECK (nick <> ''),
                                          nick_upper text GENERATED ALWAYS AS (upper(nick)) STORED,
                                          tags text[] NOT NULL DEFAULT '{}',
                                          meta jsonb);")
      (pgmalli/generate! (assoc config :schemas ["ins"]))
      (let [registry (pgmalli/registry (gen/load-file* (gen/path-for config "ins")))
            dataset (clojure.test.check.generators/generate (pgmalli/dataset-generator registry {:rows 4}) 30 7)
            statements (pgmalli/inserts registry dataset)
            counts (fn [] (str/join " " (for [t ["ins.groups" "ins.users"]]
                                          (str "IF (SELECT count(*) FROM " t ") <> " (count (get dataset t))
                                               " THEN RAISE EXCEPTION '" t " has the wrong number of rows'; END IF;"))))]
        (is (= [:ins.groups [{:overriding-value :system} :ins.users]] (map :insert-into statements)))
        (exec-sql! (str (str/join ";\n" (map #(first (honey.sql/format % {:inline true})) statements)) ";\n"
                        "DO $$ BEGIN " (counts) " END $$;"))
        (is true "every INSERT ran, identity ids kept, generated column left to the database")))))
