(ns pgmalli.impl.files-test
  "The config and the text of a generated file; no database."
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is]]
            [pgmalli.impl.files :as files]))

(deftest generated-data-must-be-edn
  (is (thrown? clojure.lang.ExceptionInfo (files/edn-string {:registry {:x [:fn (fn [_] true)]}})))
  (let [s (files/edn-string {:registry {:pg.public/t [:map [:a ['inst? {:pg/type "timestamptz"}]]]}})]
    (is (str/starts-with? s ";; generated by pgmalli"))
    (is (not (str/includes? s "#:pg")))))

(deftest unknown-config-keys-are-rejected
  (is (thrown-with-msg? clojure.lang.ExceptionInfo #"unknown config keys" (files/config {:out_dir "x"}))))
